# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build

on: workflow_dispatch

jobs:
    build-dotnet:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  working-directory: ./api
                  dotnet-version: 8.0.x
            - name: Restore dependencies
              working-directory: ./api
              run: dotnet restore
            - name: Build
              working-directory: ./api
              run: dotnet build --no-restore -c Release
            - name: Upload
              uses: actions/upload-artifact@v4.4.0
              with:
                  name: dotnet-build
                  path: ./api/bin/Release/net8.0

    build-web:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Setup Node.js environment
              uses: actions/setup-node@v4.0.3
              with:
                  working-directory: ./web
            - name: Restore dependencies
              working-directory: ./web
              run: npm ci
            - name: Build
              working-directory: ./web
              run: npm run build
            - name: Upload
              uses: actions/upload-artifact@v4.4.0
              with:
                  name: web-build
                  path: ./web/dist

    run-e2e-tests:
        runs-on: ubuntu-latest
        needs: [build-web, build-dotnet]

        services:
            mongo:
                image: mongodb/mongodb-community-server:7.0.9-ubi9
                ports:
                    - 27017:27017

        steps:
            - name: Download dotnet build
              uses: actions/download-artifact@v4.1.8
              with:
                  name: dotnet-build
                  path: api
            - name: Download web build
              uses: actions/download-artifact@v4.1.8
              with:
                  name: web-build
                  path: web
            - name: Install mongosh
              run: |
                  sudo apt-get update
                  sudo apt-get install -y wget gnupg
                  wget -q0 - https://www.mongodb.org/static/pgp/server-7.0.asc | sudo apt-key add -
                  sudo apt-get update
                  sudo apt-get install -y mongodb-mongosh
            - name: Query mongo status
              run: |
                  mongosh
                  db.serverStatus()
                  quit()
                  
            
